services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/usr/share/nginx/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: chlgustjr05@
      MYSQL_DATABASE: wargame
    volumes:
      - db_data:/var/lib/mysql
      - ./wargame.sql:/docker-entrypoint-initdb.d/wargame.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local
