services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/wargame
      - /wargame/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: chlgustjr05@
      MYSQL_DATABASE: wargame
    volumes:
      - db_data:/var/lib/mysql
      - ./wargame.sql:/docker-entrypoint-initdb.d/wargame.sql
    ports:
      - "3307:3306"

volumes:
  db_data:
    driver: local
